"""added about me + last seen cols

Revision ID: 956fab2f9240
Revises: 99a929255818
Create Date: 2020-05-25 21:08:54.291257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956fab2f9240'
down_revision = '99a929255818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
